# Generated by Django 5.2 on 2025-06-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='diplomas', verbose_name='Imagen')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de obtención')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'diploma',
                'verbose_name_plural': 'diplomas',
                'ordering': ['-date', '-created'],
            },
        ),
    ]
